### ISSUE TITLE
Save SnackVar result

### ISSUE THREAD

**Issue by raphaelleman** [Young-gonKim/SnackVar#1]
Currently, to save our result, we take a screenshot of SnackVar window. It would be possible to implement a function in SnackVar to print the alignments and the variant calling results.

Thank you by advance.

**Comment by Young-gonKim** [comment]
I guess I could work on that soon, probably during the upcoming holidays. 
Thank you for the good suggestion!

**Comment by Young-gonKim** [comment]
Would you try using newer version, V2.3.0?
You will see the 'Generate Report' button at the bottom. 
You can print the report or make PDF using 'Print' button.

**Comment by raphaelleman** [comment]
Thank you for this option, I have just one more request, Is it possible to add the name of imported trace files to the report

**Comment by raphaelleman** [comment]
Thank you, this is perfect
