### ISSUE TITLE
Possibility to search for c. position

### ISSUE THREAD

**Issue by cruckert** [Young-gonKim/SnackVar#2]
It would be nice to have an input field to jump to and mark a given c. position.

**Comment by Young-gonKim** [comment]
We added a function of jumping to the input location (Ver 2.4.0). You will find an input filed for the c. position and 'Go' button.  Please understand us that we could not fully reflect your helpful suggestions.

**Comment by cruckert** [comment]
Thank you very much for adding this feature.
