### ISSUE TITLE
Bad annotation for a double variants

### ISSUE THREAD

**Issue by raphaelleman** [Young-gonKim/SnackVar#5]
Hi,

We have patient with both a SNP homozygous (NM_007294(BRCA1):c.2612C>T) and an insertion (NM_007294(BRCA1):c.2612_2613insT), but SnackVar detects wrongly a duplication (NM_007294(BRCA1):c.2612dup).
Do you think it is possible for SnackVar to distinguish these two contiguous events.

Best regards

**Comment by Young-gonKim** [comment]
Hi, 

Thank you for the feedback. 
I think it is an exceptional scenario that SnackVar does not cover. 
Could you please send me the ab1 file after removing personal information? (through the email address on my github profile)
I could try to fix it without the data file but it would be much more effective when I do it with the file.

**Comment by raphaelleman** [comment]
Hi,

I've just send you an email (at: opaleye83@naver.com) with the ab1 files

**Comment by Young-gonKim** [comment]
The problem has been fixed, please check the version 2.4.3.
From the files you sent me, the variants are correctly called from the forward trace. 
The insertion is mis-called from the reverse trace because of the baescalling error. 
Thank you again for your feedbacks.

**Comment by raphaelleman** [comment]
Thanks, It works perfect
